#line 2 "src/lexer.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
static yyconst short int yy_acclist[425] =
    {   0,
       95,   93,   94,   90,   93,   94,   90,   94,   52,   93,
       94,   93,   94,   83,   93,   94,   54,   93,   94,   47,
       93,   94,   93,   94,   39,   93,   94,   40,   93,   94,
       48,   93,   94,   49,   93,   94,   82,   93,   94,   50,
       93,   94,   43,   93,   94,   53,   93,   94,   87,   93,
       94,   87,   93,   94,   68,   93,   94,   69,   93,   94,
       57,   93,   94,   71,   93,   94,   58,   93,   94,   67,
       93,   94,   85,   93,   94,   85,   93,   94,   37,   93,
       94,   93,   94,   38,   93,   94,   63,   93,   94,   85,
       93,   94,   85,   93,   94,   85,   93,   94,   85,   93,

       94,   85,   93,   94,   85,   93,   94,   85,   93,   94,
       85,   93,   94,   85,   93,   94,   85,   93,   94,   85,
       93,   94,   85,   93,   94,   84,   85,   93,   94,   85,
       93,   94,   85,   93,   94,   85,   93,   94,   41,   93,
       94,   64,   93,   94,   42,   93,   94,   51,   93,   94,
       62,   89,   74,   65,   79,   72,   45,   75,   46,   76,
       44,   88,   91,   73,   88,   87,   87,   87,   87,   87,
       87,   87,   87,   55,   59,   61,   60,   56,   85,   80,
       85,   85,   85,   85,   85,   85,   85,   85,    8,   85,
       85,   85,   85,   85,   85,   85,   16,   85,   85,   85,

       85,   85,   85,   85,   85,   85,   85,   85,   85,   81,
       66,   86,   70,   88,   91,   88,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       77,   78,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   14,   85,   85,   85,   18,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   88,   92,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   85,   85,    1,   85,   85,
        3,   85,    4,   85,   85,   85,   85,   85,   10,   85,

       11,   85,   85,   85,   15,   85,   85,   19,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   32,   85,   85,   85,   87,   87,   87,   88,   87,
       87,   87,   35,   85,   85,    2,   85,    5,   85,   85,
       85,   85,   85,   13,   85,   85,   85,   85,   85,   23,
       85,   85,   85,   85,   85,   85,   85,   30,   85,   85,
       85,   34,   85,   88,   87,   87,   85,   85,   85,   85,
        9,   85,   12,   85,   17,   85,   85,   85,   22,   85,
       24,   85,   25,   85,   26,   85,   27,   85,   28,   85,
       85,   85,   85,   85,   85,   85,   85,    7,   85,   85,

       85,   29,   85,   85,   85,   85,   85,   36,   85,    6,
       85,   20,   85,   21,   85,   31,   85,   33,   85,   85,
       85,   85,   85,   85
    } ;

static yyconst short int yy_accept[353] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   14,   17,
       20,   23,   25,   28,   31,   34,   37,   40,   43,   46,
       49,   52,   55,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   84,   87,   90,   93,   96,   99,  102,  105,
      108,  111,  114,  117,  120,  123,  126,  130,  133,  136,
      139,  142,  145,  148,  151,  152,  152,  153,  153,  154,
      155,  156,  156,  156,  157,  158,  159,  160,  161,  162,
      162,  163,  163,  164,  165,  166,  167,  167,  167,  168,
      169,  169,  170,  171,  172,  173,  174,  175,  176,  177,
      178,  179,  180,  180,  180,  180,  180,  181,  182,  183,

      184,  185,  186,  187,  188,  189,  191,  192,  193,  194,
      195,  196,  197,  199,  200,  201,  202,  203,  204,  205,
      206,  207,  208,  209,  210,  211,  212,  212,  212,  212,
      213,  213,  213,  213,  214,  214,  215,  215,  215,  216,
      216,  217,  218,  219,  220,  221,  222,  223,  223,  224,
      225,  226,  227,  228,  229,  230,  231,  232,  233,  233,
      233,  234,  235,  236,  237,  238,  239,  240,  241,  242,
      243,  244,  245,  246,  248,  249,  250,  252,  253,  254,
      255,  256,  257,  258,  259,  260,  261,  262,  263,  264,
      265,  266,  267,  268,  268,  268,  268,  268,  268,  268,

      268,  269,  270,  271,  272,  273,  274,  275,  276,  277,
      278,  279,  280,  280,  280,  281,  281,  282,  283,  284,
      285,  286,  286,  286,  287,  288,  290,  291,  293,  295,
      296,  297,  298,  299,  301,  303,  304,  305,  307,  308,
      310,  311,  312,  313,  314,  315,  316,  317,  318,  319,
      320,  321,  322,  324,  325,  326,  326,  326,  326,  326,
      327,  328,  329,  329,  330,  331,  332,  333,  333,  333,
      335,  336,  338,  340,  341,  342,  343,  344,  346,  347,
      348,  349,  350,  352,  353,  354,  355,  356,  357,  358,
      360,  361,  362,  364,  364,  364,  365,  366,  367,  367,

      368,  369,  370,  371,  373,  375,  377,  378,  379,  381,
      383,  385,  387,  389,  391,  392,  393,  394,  394,  394,
      395,  396,  397,  398,  400,  401,  402,  404,  405,  406,
      406,  406,  407,  408,  410,  412,  414,  416,  418,  420,
      420,  420,  421,  422,  422,  422,  423,  424,  424,  424,
      425,  425
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   27,   30,   31,
       32,   32,   32,   32,   32,   33,   32,   32,   32,   34,
       32,   32,   32,   32,   35,   32,   32,   36,   32,   32,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   32,   51,   52,   53,   54,
       55,   56,   32,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[70] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    6,    7,
        1,    1,    1,    1,    1,    3,    7,    7,    7,    7,
        7,    8,    8,    8,    9,    8,    1,    9,    1,    1,
        8,    6,    6,    7,    7,    7,    6,    8,    8,    8,
        8,    8,    8,    9,    8,    8,    9,    8,    9,    9,
        9,    8,    9,    8,    8,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[383] =
    {   0,
        0,    0,  799, 1154, 1154, 1154,  774,   65, 1154,  773,
       63,  758, 1154, 1154,  771,   59, 1154,   60,   58,   69,
       88,   79, 1154, 1154,   56,  770,   64, 1154,  755,   91,
     1154,   55, 1154,  763,   63,   56,   73,   94,   64,   90,
       95,   67,  107,   82,   89,  108,   88,  117,  118,  125,
     1154,   93, 1154, 1154, 1154,  154, 1154,  146, 1154, 1154,
     1154,  777,  150, 1154, 1154, 1154, 1154, 1154, 1154,  769,
      168,  772,    0, 1154,  198,  203,  159,  222,  191,  213,
      767,  219,  242,  224,  231,  235,  758, 1154, 1154, 1154,
      748,  733,   78,  157,  732,    0, 1154,  128,  138,  144,

      134,  146,  152,  153,   35,  170,  174,  187,  215,  201,
      229,  231,  731,  240,  173,  255,  242,  258,  243,  251,
      260,  267,  269,  270, 1154, 1154,  310,    0,    0, 1154,
      313,    0,    0, 1154,  320, 1154,  756,  185,    0,  291,
      323,  301,  311,  295,  316,  285,  317,    0,  346,  324,
      331,  352,  353,  357,  362,  366, 1154, 1154,    0,    0,
      327,  274,  334,  158,  362,  288,  335,  336,  372,  365,
      378,  381,  382,  729,  383,  385,  728,  391,  387,  369,
      244,  392,  394,  395,  396,  398,  402,  404,  405,  406,
      322,  409,  407,  447,    0,  481,  444,    0,  756,  449,

      484, 1154,  437,  438,  422, 1154,  419,  454,  431,  731,
      711,  461,  473,  482,  485,  528,  497,  500,  499,  509,
      520,    0,    0,  438,  437,  719,  440,  718,  717,  446,
      442,  502,  443,  716,  715,  501,  512,  714,  516,  704,
      518,  525,  526,  527,  528,  529,  535,  537,  549,  550,
      540,  541,  703,  539,  553,  563,    0,    0,    0, 1154,
      557,  567,  585,  592,  580,  581,  585,    0,    0,  702,
      569,  701,  700,  568,  586,  588,  592,  699,  590,  570,
      593,  597,  698,  604,  609,  610,  612,  439,  614,  697,
      615,  617,  696,    0,    0, 1154,  624,  628,    0,  671,

      620,  626,  624,  689,  686,  685,  627,  630,  684,  674,
      672,  670,  669,  668,  632,  639,  640,  701,  696,  731,
      761,  634,  649,  658,  637,  644,  643,  666,  687,  791,
        0,  821,  851,  559,  558,  484,  408,  358,  320,  881,
        0,  911,  941,  971,    0, 1001,  286,  688,  225,  103,
     1154, 1048, 1057, 1061, 1068, 1075, 1084, 1093, 1098, 1100,
     1102, 1104, 1106, 1108, 1110, 1112, 1114, 1116, 1118, 1120,
     1122, 1124, 1126, 1128, 1130, 1132, 1134, 1136, 1140, 1142,
     1144, 1146
    } ;

static yyconst short int yy_def[383] =
    {   0,
      351,    1,  351,  351,  351,  351,  351,  352,  351,  351,
      351,  353,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  354,  354,
      351,  351,  351,  351,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      351,  351,  351,  351,  351,  352,  351,  355,  351,  351,
      351,  351,  356,  351,  351,  351,  351,  351,  351,  351,
      351,  357,  358,  351,  351,  351,  351,  351,  351,  351,
      359,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  354,  351,  352,  353,  360,  351,  354,  354,  354,

      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  351,  351,  352,  361,  362,  351,
      351,  363,  364,  351,  351,  351,  357,  357,  358,  351,
      351,  351,  351,  351,  351,  351,  351,  365,  359,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  366,  367,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  352,  368,  352,  351,  369,  364,  351,

      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  365,  365,  351,  351,  351,  351,  351,  351,
      351,  370,  371,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  352,  372,  196,  373,  351,
      351,  351,  351,  351,  351,  351,  351,  374,  375,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  376,  377,  351,  351,  351,  378,  354,

      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  196,  379,  300,
      300,  354,  354,  354,  354,  354,  354,  354,  354,  196,
      380,  300,  300,  354,  354,  354,  354,  354,  354,  196,
      381,  300,  300,  196,  382,  300,  354,  352,  351,  354,
        0,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351
    } ;

static yyconst short int yy_nxt[1224] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   29,
       29,   29,   30,   29,   29,   29,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   29,   43,
       29,   44,   29,   29,   29,   29,   45,   46,   47,   48,
       49,   50,   29,   29,   29,   51,   52,   53,   54,   57,
       60,   65,   93,   70,   67,   71,   71,   71,   87,   88,
       72,  168,   66,   68,   69,   73,   61,   90,   91,   96,
       98,   99,   74,   93,   75,   94,   83,   83,   83,   95,

       93,   93,   58,   75,   93,   76,   76,   77,   78,  105,
       93,   84,  159,   85,   96,  100,  125,   78,  106,   93,
       79,  112,   80,   81,   78,   93,   93,   93,   93,  101,
       86,   93,   93,   78,  116,  102,  115,  159,   85,   82,
       93,  107,  103,  108,   93,   93,  110,   80,  104,  111,
       81,  121,  109,  113,   93,   93,  117,  118,   57,  126,
      114,   57,   93,  127,  127,   93,  119,  131,  131,  120,
      122,   93,  123,  124,   75,   93,   77,   77,   77,  164,
      128,   93,  161,   93,  132,   71,   71,   71,   78,   93,
       93,   58,  162,  166,   58,   93,  138,  135,  136,  227,

      136,  202,  163,  165,   78,  128,  167,   93,  129,  132,
       93,   93,  133,  135,  136,   71,   71,   71,   75,  136,
       76,   76,   77,  142,   93,  143,  178,  135,  136,  169,
      136,  170,   78,  130,  140,   79,  140,   80,   93,  141,
      141,  141,  144,  135,  136,  145,  171,  146,   78,  136,
      143,  150,   93,  143,   82,  173,  152,   75,  153,   83,
       83,   83,   80,  154,  147,  146,   93,  150,   93,  153,
      151,   78,  146,  172,   84,  144,   85,   93,  143,   93,
       93,   93,  155,  153,  185,  174,  156,   78,   93,  175,
      146,  176,   93,   86,  153,   93,  182,   93,  177,  186,

      187,   85,  179,  243,   93,  183,   93,   93,  141,  141,
      141,   93,  180,  181,   57,  188,  189,  210,  191,  193,
      192,  130,  184,   93,  190,   93,  225,  194,  194,  206,
      197,  197,  200,  203,  200,  143,  211,  201,  201,  201,
      141,  141,  141,  204,  229,  146,  207,   58,  208,  150,
      209,  209,  144,  136,  206,  136,  207,   93,  206,   93,
      143,  214,  205,  150,   93,  143,  253,  144,  212,  136,
      146,   93,   93,   93,  136,  209,  209,  232,  215,  216,
      217,  224,  219,  206,  203,  204,  153,  146,  226,  220,
      143,  209,  230,  231,  150,   93,  209,  218,  150,   93,

      153,  216,   93,  144,  205,  217,   93,  228,  144,   93,
      234,  153,  146,  221,  233,   93,  209,  219,   93,   93,
       93,  209,   93,  237,   93,  153,  236,  242,   93,   93,
      235,   93,   93,   93,  239,   93,  241,  238,  240,   93,
      246,   93,   93,   93,   93,   93,   93,  245,  244,  250,
      254,   57,  130,  206,  247,  252,  206,  248,  255,  251,
      249,   62,   62,  210,  256,  256,  201,  201,  201,  207,
      207,  206,  206,  207,   93,   93,   93,   93,  206,   93,
       93,  206,  211,   93,   58,   57,  203,  314,  209,  270,
      272,  274,  271,  150,  276,  209,  206,  206,  258,  258,

      258,  201,  201,  201,  273,  144,  216,  258,  258,  258,
      258,  258,  219,  209,  136,  216,  136,  261,   58,  262,
      209,   93,  258,  258,  258,  258,  258,  258,  216,  265,
      136,  146,  150,  206,  262,  136,  144,  216,   93,   93,
      263,  203,  263,  209,  262,  264,  264,  264,  266,   93,
      207,  267,  150,   93,  209,   93,  146,  277,  206,  262,
      144,  275,   93,   93,   93,   93,   93,   57,  209,  279,
      278,  219,   93,  284,   93,  280,   93,   93,   93,  209,
      287,  281,  282,  285,  286,  283,   93,   93,  291,  203,
       93,  262,  288,  290,  289,   93,   93,  292,  293,  204,

       58,  146,  264,  264,  264,   93,   93,   93,  144,  264,
      264,  264,  297,  150,  209,  209,  262,  150,  205,  262,
      301,  302,  296,   93,  296,   93,  146,   93,  307,   93,
       93,  144,  298,  304,   93,  306,  219,  303,  296,  209,
      209,   93,  308,  296,  262,  305,   93,   93,  310,   93,
      309,   93,   93,  312,   93,  311,  203,   93,  209,  315,
      150,   93,  209,   93,   93,  322,  317,   93,  316,   93,
      313,   93,  325,  326,   93,  144,   93,   93,  327,  219,
       93,   93,  324,  209,  328,  323,   93,  209,  321,  321,
      321,  329,   57,  336,  335,   93,  334,  321,  321,  321,

      321,  321,  337,   93,  130,   93,   93,   93,   93,   93,
      338,   93,  321,  321,  321,  321,  321,  321,  330,  330,
      330,   93,   93,   93,   93,   58,   93,  330,  330,  330,
      330,  330,  339,   93,   93,   93,   93,   93,   93,   93,
       93,   93,  330,  330,  330,  330,  330,  330,  332,  332,
      332,   93,   93,   93,   93,   93,   93,  332,  332,  332,
      332,  332,  260,  260,  130,   93,   93,  138,   93,   63,
       93,  158,  332,  332,  332,  332,  332,  332,  333,  333,
      333,  157,  148,  138,  134,  130,   97,  333,  333,  333,
      333,  333,   93,   89,   64,   63,   59,   55,  351,  351,

      351,  351,  333,  333,  333,  333,  333,  333,  340,  340,
      340,  351,  351,  351,  351,  351,  351,  340,  340,  340,
      340,  340,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  340,  340,  340,  340,  340,  340,  342,  342,
      342,  351,  351,  351,  351,  351,  351,  342,  342,  342,
      342,  342,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  342,  342,  342,  342,  342,  342,  343,  343,
      343,  351,  351,  351,  351,  351,  351,  343,  343,  343,
      343,  343,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  343,  343,  343,  343,  343,  343,  344,  344,

      344,  351,  351,  351,  351,  351,  351,  344,  344,  344,
      344,  344,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  344,  344,  344,  344,  344,  344,  346,  346,
      346,  351,  351,  351,  351,  351,  351,  346,  346,  346,
      346,  346,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  346,  346,  346,  346,  346,  346,  347,  347,
      347,  351,  351,  351,  351,  351,  351,  347,  347,  347,
      347,  347,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  347,  347,  347,  347,  347,  347,  348,  348,
      348,  351,  351,  351,  351,  351,  351,  348,  348,  348,

      348,  348,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  348,  348,  348,  348,  348,  348,  350,  350,
      350,  351,  351,  351,  351,  351,  351,  350,  350,  350,
      350,  350,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  350,  350,  350,  350,  350,  350,   56,  351,
       56,   56,   56,   56,   56,   56,   56,   62,  351,   62,
      351,   62,   62,   62,   62,   62,   92,   92,   92,   92,
       56,   56,  351,   56,  351,  351,   56,   62,   62,  351,
       62,  351,  351,   62,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  139,  351,  139,  139,  139,  139,  139,

      139,  139,  149,  149,  149,  160,  160,  195,  195,  196,
      196,  198,  198,  199,  199,  213,  213,  222,  222,  223,
      223,  257,  257,  259,  259,  268,  268,  269,  269,  294,
      294,  295,  295,  299,  299,  300,  300,  318,  318,  319,
      319,  320,  320,  331,  351,  331,  331,  341,  341,  345,
      345,  349,  349,    3,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,

      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351
    } ;

static yyconst short int yy_chk[1224] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    8,
       11,   16,  105,   19,   18,   19,   19,   19,   25,   25,
       20,  105,   16,   18,   18,   20,   11,   27,   27,   32,
       35,   35,   20,   36,   22,   30,   22,   22,   22,   30,

       35,   39,    8,   21,   42,   21,   21,   21,   22,   39,
       37,   22,   93,   22,   32,   36,   52,   21,   39,   44,
       21,   42,   21,   21,   22,   47,   45,   40,   30,   37,
       22,   38,   41,   21,   45,   38,   44,   93,   22,   21,
      350,   40,   38,   40,   43,   46,   41,   21,   38,   41,
       21,   47,   40,   43,   48,   49,   46,   46,   56,   52,
       43,   94,   50,   58,   58,   98,   46,   63,   63,   46,
       48,  101,   49,   50,   77,   99,   77,   77,   77,  101,
       58,  100,   98,  102,   63,   71,   71,   71,   77,  103,
      104,   56,   99,  103,   94,  164,  138,   71,   71,  164,

       71,  138,  100,  102,   77,   58,  104,  106,   58,   63,
      115,  107,   63,   71,   71,   75,   75,   75,   76,   71,
       76,   76,   76,   79,  108,   79,  115,   75,   75,  106,
       75,  107,   76,  349,   78,   76,   78,   76,  110,   78,
       78,   78,   79,   75,   75,   80,  108,   80,   76,   75,
       79,   82,  109,   82,   76,  110,   84,   83,   84,   83,
       83,   83,   76,   85,   80,   85,  111,   86,  112,   86,
       82,   83,   80,  109,   83,   84,   83,  114,   82,  117,
      119,  181,   85,   84,  119,  111,   86,   83,  120,  112,
       85,  114,  116,   83,   86,  118,  117,  121,  114,  119,

      120,   83,  116,  181,  122,  118,  123,  124,  140,  140,
      140,  162,  116,  116,  127,  121,  122,  146,  123,  124,
      123,  131,  118,  347,  122,  166,  162,  127,  127,  144,
      131,  131,  135,  142,  135,  142,  146,  135,  135,  135,
      141,  141,  141,  143,  166,  143,  144,  127,  145,  147,
      145,  147,  142,  141,  144,  141,  150,  339,  150,  191,
      142,  149,  143,  151,  161,  151,  191,  145,  147,  141,
      143,  163,  167,  168,  141,  145,  147,  168,  149,  149,
      149,  161,  151,  150,  152,  153,  152,  153,  163,  154,
      151,  154,  167,  167,  155,  338,  155,  149,  156,  165,

      156,  149,  170,  152,  153,  149,  180,  165,  154,  169,
      170,  152,  153,  155,  169,  171,  154,  156,  172,  173,
      175,  155,  176,  173,  179,  156,  172,  180,  178,  182,
      171,  183,  184,  185,  176,  186,  179,  175,  178,  187,
      184,  188,  189,  190,  193,  337,  192,  183,  182,  188,
      192,  194,  197,  207,  185,  190,  205,  186,  193,  189,
      187,  197,  197,  209,  194,  194,  200,  200,  200,  203,
      204,  203,  204,  205,  225,  224,  288,  227,  207,  231,
      233,  205,  209,  230,  194,  196,  208,  288,  208,  224,
      227,  231,  225,  212,  233,  212,  203,  204,  196,  196,

      196,  201,  201,  201,  230,  208,  213,  196,  196,  196,
      196,  196,  212,  208,  201,  214,  201,  215,  196,  215,
      212,  336,  196,  196,  196,  196,  196,  196,  213,  217,
      201,  217,  218,  219,  218,  201,  215,  214,  236,  232,
      216,  220,  216,  220,  215,  216,  216,  216,  217,  237,
      219,  218,  221,  239,  221,  241,  217,  236,  219,  218,
      220,  232,  242,  243,  244,  245,  246,  256,  220,  239,
      237,  221,  247,  245,  248,  241,  254,  251,  252,  221,
      248,  242,  243,  246,  247,  244,  249,  250,  252,  261,
      255,  261,  249,  251,  250,  335,  334,  254,  255,  262,

      256,  262,  263,  263,  263,  274,  271,  280,  261,  264,
      264,  264,  265,  266,  265,  266,  261,  267,  262,  267,
      271,  274,  264,  275,  264,  276,  262,  279,  280,  277,
      281,  265,  266,  276,  282,  279,  267,  275,  264,  265,
      266,  284,  281,  264,  267,  277,  285,  286,  284,  287,
      282,  289,  291,  286,  292,  285,  297,  301,  297,  289,
      298,  303,  298,  302,  307,  301,  292,  308,  291,  315,
      287,  322,  307,  308,  325,  297,  316,  317,  315,  298,
      327,  326,  303,  297,  316,  302,  323,  298,  300,  300,
      300,  317,  348,  325,  323,  324,  322,  300,  300,  300,

      300,  300,  326,  328,  319,  314,  313,  312,  300,  311,
      328,  310,  300,  300,  300,  300,  300,  300,  318,  318,
      318,  309,  306,  305,  329,  348,  304,  318,  318,  318,
      318,  318,  329,  293,  290,  283,  278,  273,  272,  270,
      253,  240,  318,  318,  318,  318,  318,  318,  320,  320,
      320,  238,  235,  234,  229,  228,  226,  320,  320,  320,
      320,  320,  211,  210,  199,  177,  174,  137,  113,   95,
       92,   91,  320,  320,  320,  320,  320,  320,  321,  321,
      321,   87,   81,   72,   70,   62,   34,  321,  321,  321,
      321,  321,   29,   26,   15,   12,   10,    7,    3,    0,

        0,    0,  321,  321,  321,  321,  321,  321,  330,  330,
      330,    0,    0,    0,    0,    0,    0,  330,  330,  330,
      330,  330,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  330,  330,  330,  330,  330,  330,  332,  332,
      332,    0,    0,    0,    0,    0,    0,  332,  332,  332,
      332,  332,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  332,  332,  332,  332,  332,  332,  333,  333,
      333,    0,    0,    0,    0,    0,    0,  333,  333,  333,
      333,  333,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  333,  333,  333,  333,  333,  333,  340,  340,

      340,    0,    0,    0,    0,    0,    0,  340,  340,  340,
      340,  340,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  340,  340,  340,  340,  340,  340,  342,  342,
      342,    0,    0,    0,    0,    0,    0,  342,  342,  342,
      342,  342,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  342,  342,  342,  342,  342,  342,  343,  343,
      343,    0,    0,    0,    0,    0,    0,  343,  343,  343,
      343,  343,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  343,  343,  343,  343,  343,  343,  344,  344,
      344,    0,    0,    0,    0,    0,    0,  344,  344,  344,

      344,  344,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  344,  344,  344,  344,  344,  344,  346,  346,
      346,    0,    0,    0,    0,    0,    0,  346,  346,  346,
      346,  346,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  346,  346,  346,  346,  346,  346,  352,    0,
      352,  352,  352,  352,  352,  352,  352,  353,    0,  353,
        0,  353,  353,  353,  353,  353,  354,  354,  354,  354,
      355,  355,    0,  355,    0,    0,  355,  356,  356,    0,
      356,    0,    0,  356,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  358,    0,  358,  358,  358,  358,  358,

      358,  358,  359,  359,  359,  360,  360,  361,  361,  362,
      362,  363,  363,  364,  364,  365,  365,  366,  366,  367,
      367,  368,  368,  369,  369,  370,  370,  371,  371,  372,
      372,  373,  373,  374,  374,  375,  375,  376,  376,  377,
      377,  378,  378,  379,    0,  379,  379,  380,  380,  381,
      381,  382,  382,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,

      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex/lexer.l"
#define INITIAL 0
#line 5 "lex/lexer.l"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "symtable.h"
#include "parser.h"

extern FILE* yyin;

#line 826 "src/lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 59 "lex/lexer.l"


#line 980 "src/lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 352 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1154 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 61 "lex/lexer.l"
{return AUTO;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 62 "lex/lexer.l"
{return BREAK;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "lex/lexer.l"
{return CASE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 64 "lex/lexer.l"
{return CHAR;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 65 "lex/lexer.l"
{return CONST;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 66 "lex/lexer.l"
{return CONTINUE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "lex/lexer.l"
{return DEFAULT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "lex/lexer.l"
{return DO;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "lex/lexer.l"
{return DOUBLE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 70 "lex/lexer.l"
{return ELSE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "lex/lexer.l"
{return ENUM;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "lex/lexer.l"
{return EXTERN;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "lex/lexer.l"
{return FLOAT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "lex/lexer.l"
{return FOR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "lex/lexer.l"
{return GOTO;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 76 "lex/lexer.l"
{return IF;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 77 "lex/lexer.l"
{return INLINE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 78 "lex/lexer.l"
{return INT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 79 "lex/lexer.l"
{return LONG;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 80 "lex/lexer.l"
{return REGISTER;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 81 "lex/lexer.l"
{return RESTRICT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 82 "lex/lexer.l"
{return RETURN;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 83 "lex/lexer.l"
{return SHORT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 84 "lex/lexer.l"
{return SIGNED;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 85 "lex/lexer.l"
{return SIZEOF;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 86 "lex/lexer.l"
{return STATIC;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 87 "lex/lexer.l"
{return STRUCT;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 88 "lex/lexer.l"
{return SWITCH;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 89 "lex/lexer.l"
{return TYPEDEF;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 90 "lex/lexer.l"
{return UNION;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 91 "lex/lexer.l"
{return UNSIGNED;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 92 "lex/lexer.l"
{return VOID;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 93 "lex/lexer.l"
{return VOLATILE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 94 "lex/lexer.l"
{return WHILE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 95 "lex/lexer.l"
{return BOOL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 96 "lex/lexer.l"
{return COMPLEX;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 98 "lex/lexer.l"
{return '[';}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 99 "lex/lexer.l"
{return ']';}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 100 "lex/lexer.l"
{return '(';}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 101 "lex/lexer.l"
{return ')';}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 102 "lex/lexer.l"
{return '{';}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 103 "lex/lexer.l"
{return '}';}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 104 "lex/lexer.l"
{return '.';}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 105 "lex/lexer.l"
{return FLECHA;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 106 "lex/lexer.l"
{return MASMAS;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 107 "lex/lexer.l"
{return MENOSMENOS;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 108 "lex/lexer.l"
{return '&';}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 109 "lex/lexer.l"
{return '*';}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 110 "lex/lexer.l"
{return '+';}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 111 "lex/lexer.l"
{return '-';}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 112 "lex/lexer.l"
{return '~';}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 113 "lex/lexer.l"
{return '!';}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 114 "lex/lexer.l"
{return '/';}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 115 "lex/lexer.l"
{return '%';}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 116 "lex/lexer.l"
{return SHIFT_LEFT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 117 "lex/lexer.l"
{return SHIFT_RIGHT;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 118 "lex/lexer.l"
{return '<';}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 119 "lex/lexer.l"
{return '>';}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 120 "lex/lexer.l"
{return MENOR_IGUAL;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 121 "lex/lexer.l"
{return MAYOR_IGUAL;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 122 "lex/lexer.l"
{return IGUALIGUAL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 123 "lex/lexer.l"
{return DIFERENTE;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 124 "lex/lexer.l"
{return '^';}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 125 "lex/lexer.l"
{return '|';}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 126 "lex/lexer.l"
{return AND;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 127 "lex/lexer.l"
{return OR;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 128 "lex/lexer.l"
{return '?';}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 129 "lex/lexer.l"
{return ':';}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 130 "lex/lexer.l"
{return ';';}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 131 "lex/lexer.l"
{return VARIARG;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 132 "lex/lexer.l"
{return '=';}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 133 "lex/lexer.l"
{return ASIGN_MULT;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 134 "lex/lexer.l"
{return ASIGN_DIV;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 135 "lex/lexer.l"
{return ASIGN_MOD;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 136 "lex/lexer.l"
{return ASIGN_SUM;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 137 "lex/lexer.l"
{return ASIGN_RESTA;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 138 "lex/lexer.l"
{return ASIGN_SHIFT_LEFT;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 139 "lex/lexer.l"
{return ASIGN_SHIFT_RIGHT;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 140 "lex/lexer.l"
{return ASIGN_BITWISE_AND;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 141 "lex/lexer.l"
{return ASIGN_BITWISE_XOR;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 142 "lex/lexer.l"
{return ASIGN_BITWISE_OR;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 143 "lex/lexer.l"
{return ',';}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 144 "lex/lexer.l"
{return '#';}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 146 "lex/lexer.l"
{return 't';}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 148 "lex/lexer.l"
{yylval.strval = strdup(yytext); return IDENTIFIER;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 149 "lex/lexer.l"
{return CHAR_CONST;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 150 "lex/lexer.l"
{return INT_CONST;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 151 "lex/lexer.l"
{return REAL_CONST;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 152 "lex/lexer.l"
{return STRING_LITERAL;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 153 "lex/lexer.l"
{}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 154 "lex/lexer.l"
{}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 155 "lex/lexer.l"
{}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 157 "lex/lexer.l"
{printf("\nLinea %i: Error Lexico \"%s\"\n", yylineno, yytext);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 159 "lex/lexer.l"
ECHO;
	YY_BREAK
#line 1541 "src/lexer.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 352 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 352 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 351);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 159 "lex/lexer.l"


int yywrap(void)
{
    return 1;
}